#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Mar  3 23:26:25 2018

@author: chengyu
"""

import os 
import csv
from gensim.models.word2vec import Word2Vec

import sklearn.manifold               # visualize high dimentions data 
import multiprocessing 
import os               
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns

#%%
## load models 
data_path = os.path.join('data','imf_160.w2v')
imf_w2v = Word2Vec.load(data_path)
model = imf_w2v.wv
vocabs = model.vocab.keys()

#%%
tsne = sklearn.manifold.TSNE(n_components=2, random_state=0,verbose=1, perplexity=40, n_iter=200)
all_word_vectors_matrix = imf_w2v.wv.vectors[:10000]
vocabs= vocabs[:10000]
all_word_vectors_matrix_2d = tsne.fit_transform(all_word_vectors_matrix)   ## fit the embeding into tsne model

#%%
data =[
        (word, coords[0], coords[1])
        for word, coords in [
            (word, all_word_vectors_matrix_2d[thrones2vec.wv.vocab[word].index])
            for word in imf_w2v.wv.vocab
        ]
      ]
